name: Restrict PRs to Major

on:
  pull_request:
    branches:
      - '[0-9]+x'

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          if [[ ! "$SOURCE_BRANCH" =~ ^(hotfix|bugfix|release)/.* && "$SOURCE_BRANCH" != "release" ]]; then
            echo "❌ ERRO: PRs para '*x' só podem vir de 'hotfix/*' ou 'bugfix/*'. ou 'release/* ou 'bugfix/*'. ou 'release'."
            exit 1
          fi
