name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  check-source-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Validate source branch
        run: |
          SOURCE_BRANCH="${{ github.head_ref }}"
          if [[ ! "$SOURCE_BRANCH" =~ ^(release|hotfix)/.* && "$SOURCE_BRANCH" != "release" ]]; then
            echo "❌ ERRO: PRs para 'main' só podem vir de 'release/*' ou 'hotfix/*'."
            exit 1
          fi
